export interface CourseItem {
  id: string;
  title: string;
  category: 'Hardware' | 'Software' | 'Data Science';
  level: 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';
  description: string;
  instructor: string;
  rating: number;
  ratingCount: number;
  price: string;
  originalPrice: string;
  duration: string;
  tag: 'Bestseller' | 'Hot & New' | 'New' | 'Top Rated' | '';
  icon: string;
  gradient: string;
}

export const COURSES_DATA: CourseItem[] = [
  // ================= HARDWARE CATEGORY =================
  {
    id: 'hw-course-1',
    title: 'Introduction to Electronics & Breadboarding',
    category: 'Hardware',
    level: 'Beginner',
    description: 'Learn basic components, voltage dividers, series & parallel circuits, and resistor color coding.',
    instructor: 'Instructor Kenji',
    rating: 4.7,
    ratingCount: 342,
    price: '$10.99',
    originalPrice: '$29.99',
    duration: '4h 30m',
    tag: 'New',
    icon: '🔌',
    gradient: 'from-amber-500 to-orange-600'
  },
  {
    id: 'hw-course-2',
    title: 'Arduino Programming for Complete Beginners',
    category: 'Hardware',
    level: 'Beginner',
    description: 'Code your first microcontroller. Learn digital I/O, analog reading, serial communication, and basic sensor reading.',
    instructor: 'Sarah Chen',
    rating: 4.8,
    ratingCount: 1204,
    price: '$12.99',
    originalPrice: '$49.99',
    duration: '8h 15m',
    tag: 'Bestseller',
    icon: '🤖',
    gradient: 'from-blue-500 to-indigo-600'
  },
  {
    id: 'hw-course-3',
    title: 'Microcontroller Architecture & Register Configuration',
    category: 'Hardware',
    level: 'Intermediate',
    description: 'Deep dive into GPIO registers, timer configurations, hardware interrupts, and memory-mapped peripheral I/O on ARM Cortex.',
    instructor: 'Instructor Kenji',
    rating: 4.6,
    ratingCount: 620,
    price: '$14.99',
    originalPrice: '$69.99',
    duration: '12h 40m',
    tag: 'Top Rated',
    icon: '📟',
    gradient: 'from-red-500 to-rose-600'
  },
  {
    id: 'hw-course-4',
    title: 'PCB Design Masterclass with Altium Designer',
    category: 'Hardware',
    level: 'Intermediate',
    description: 'Create professional schematics, route high-density multi-layer printed circuit boards, and generate Gerber files for manufacturing.',
    instructor: 'Senior Supervisor Kenji',
    rating: 4.9,
    ratingCount: 850,
    price: '$19.99',
    originalPrice: '$99.99',
    duration: '15h 20m',
    tag: 'Bestseller',
    icon: '🗺️',
    gradient: 'from-green-500 to-teal-600'
  },
  {
    id: 'hw-course-5',
    title: 'Embedded Real-Time Operating Systems (FreeRTOS)',
    category: 'Hardware',
    level: 'Advanced',
    description: 'Master RTOS task scheduling, queues, semaphores, mutexes, and write deterministic low-latency multi-threaded applications.',
    instructor: 'Instructor Kenji',
    rating: 4.7,
    ratingCount: 451,
    price: '$24.99',
    originalPrice: '$119.99',
    duration: '14h 10m',
    tag: 'Hot & New',
    icon: '⚙️',
    gradient: 'from-violet-600 to-purple-800'
  },
  {
    id: 'hw-course-6',
    title: 'High-Speed Digital Design & Signal Integrity',
    category: 'Hardware',
    level: 'Advanced',
    description: 'Analyze high-frequency transmission lines, impedance matching, crosstalk, electromagnetic interference, and timing skew.',
    instructor: 'Sarah Chen',
    rating: 4.8,
    ratingCount: 189,
    price: '$29.99',
    originalPrice: '$149.99',
    duration: '10h 45m',
    tag: '',
    icon: '⚡',
    gradient: 'from-pink-500 to-purple-600'
  },
  {
    id: 'hw-course-7',
    title: 'Bare-Metal ARM Cortex Firmware Engineering',
    category: 'Hardware',
    level: 'Expert',
    description: 'Write startup scripts, custom memory linkers, vector tables, interrupt handlers, and highly optimized assembly routines.',
    instructor: 'Lead Instructor Kenji',
    rating: 4.9,
    ratingCount: 131,
    price: '$39.99',
    originalPrice: '$199.99',
    duration: '18h 35m',
    tag: 'Top Rated',
    icon: '🧠',
    gradient: 'from-slate-700 to-slate-900'
  },
  {
    id: 'hw-course-8',
    title: 'Hardware Cryptography & Secure Trust Execution',
    category: 'Hardware',
    level: 'Expert',
    description: 'Implement secure boot elements, hardware-based root of trust, crypto coprocessors, and guard against side-channel analysis.',
    instructor: 'Senior Certification Supervisor',
    rating: 4.8,
    ratingCount: 75,
    price: '$45.99',
    originalPrice: '$249.99',
    duration: '13h 15m',
    tag: 'New',
    icon: '🔐',
    gradient: 'from-zinc-800 to-neutral-950'
  },

  // ================= SOFTWARE CATEGORY =================
  {
    id: 'sw-course-1',
    title: 'Modern Web Development Fundamentals (HTML/CSS/JS)',
    category: 'Software',
    level: 'Beginner',
    description: 'Understand core browser mechanics, flexbox/grid layout design, responsive media, and modern asynchronous JavaScript.',
    instructor: 'Sarah Chen',
    rating: 4.7,
    ratingCount: 2345,
    price: '$10.99',
    originalPrice: '$39.99',
    duration: '11h 20m',
    tag: 'Bestseller',
    icon: '🌐',
    gradient: 'from-sky-400 to-blue-600'
  },
  {
    id: 'sw-course-2',
    title: 'Introduction to Programming with Python',
    category: 'Software',
    level: 'Beginner',
    description: 'Learn conditional branching, loops, core functions, data structures, and object-oriented programming with Python.',
    instructor: 'Alex Mercer',
    rating: 4.8,
    ratingCount: 4502,
    price: '$10.99',
    originalPrice: '$49.99',
    duration: '9h 50m',
    tag: 'Top Rated',
    icon: '🐍',
    gradient: 'from-yellow-400 to-amber-600'
  },
  {
    id: 'sw-course-3',
    title: 'React 18 & Advanced Client State Architecture',
    category: 'Software',
    level: 'Intermediate',
    description: 'Master React functional hooks, context state preservation, Redux Toolkit, React Query, and virtual DOM paint optimizations.',
    instructor: 'Sarah Chen',
    rating: 4.9,
    ratingCount: 1820,
    price: '$14.99',
    originalPrice: '$79.99',
    duration: '16h 30m',
    tag: 'Hot & New',
    icon: '🥞',
    gradient: 'from-cyan-400 to-teal-600'
  },
  {
    id: 'sw-course-4',
    title: 'Node.js REST API Architecture & Express',
    category: 'Software',
    level: 'Intermediate',
    description: 'Build robust server-side routing systems, express custom middlewares, request validators, and JWT access token guards.',
    instructor: 'Alex Mercer',
    rating: 4.6,
    ratingCount: 912,
    price: '$12.99',
    originalPrice: '$59.99',
    duration: '10h 15m',
    tag: '',
    icon: '🛡️',
    gradient: 'from-emerald-500 to-green-700'
  },
  {
    id: 'sw-course-5',
    title: 'Advanced TypeScript & Enterprise Design Patterns',
    category: 'Software',
    level: 'Advanced',
    description: 'Leverage generic type utilities, mapped types, conditional compilation, decorators, and write modular, testable SOLID code.',
    instructor: 'Lead Instructor Kenji',
    rating: 4.8,
    ratingCount: 412,
    price: '$19.99',
    originalPrice: '$99.99',
    duration: '12h 10m',
    tag: 'Top Rated',
    icon: '⌨️',
    gradient: 'from-indigo-600 to-violet-800'
  },
  {
    id: 'sw-course-6',
    title: 'Microservices with NestJS & RabbitMQ Messaging',
    category: 'Software',
    level: 'Advanced',
    description: 'Build enterprise-grade distributed systems. Implement event-driven services, direct/topic exchange routing, and database replication.',
    instructor: 'Alex Mercer',
    rating: 4.7,
    ratingCount: 305,
    price: '$24.99',
    originalPrice: '$119.99',
    duration: '14h 50m',
    tag: 'New',
    icon: '📦',
    gradient: 'from-rose-600 to-purple-700'
  },
  {
    id: 'sw-course-7',
    title: 'Distributed System Design & Micro-Cache Sharding',
    category: 'Software',
    level: 'Expert',
    description: 'Learn global load balancing, high-performance Redis cache layers, write-through policies, database partitions, and horizontal scale.',
    instructor: 'Sarah Chen',
    rating: 4.9,
    ratingCount: 1420,
    price: '$34.99',
    originalPrice: '$179.99',
    duration: '22h 10m',
    tag: 'Bestseller',
    icon: '🏗️',
    gradient: 'from-purple-600 to-indigo-900'
  },
  {
    id: 'sw-course-8',
    title: 'Kubernetes Orchestration & Secure Cloud DevOps',
    category: 'Software',
    level: 'Expert',
    description: 'Construct automated multi-stage Docker builds, orchestrate high-availability Kubernetes pods, configure ingress controllers, and secure CI/CD pipelines.',
    instructor: 'Platform Superuser Sarah',
    rating: 4.8,
    ratingCount: 256,
    price: '$39.99',
    originalPrice: '$199.99',
    duration: '17h 40m',
    tag: 'Hot & New',
    icon: '☸️',
    gradient: 'from-blue-600 to-slate-800'
  },

  // ================= DATA SCIENCE CATEGORY =================
  {
    id: 'ds-course-1',
    title: 'Practical Data Analytics with Microsoft Excel',
    category: 'Data Science',
    level: 'Beginner',
    description: 'Learn formulas, aggregate pivot tables, advanced lookup functions, linear trend forecasts, and business reporting dashboards.',
    instructor: 'Alex Mercer',
    rating: 4.6,
    ratingCount: 3210,
    price: '$10.99',
    originalPrice: '$27.99',
    duration: '7h 15m',
    tag: 'Bestseller',
    icon: '📊',
    gradient: 'from-green-600 to-emerald-800'
  },
  {
    id: 'ds-course-2',
    title: 'Mathematics Foundations for Machine Learning',
    category: 'Data Science',
    level: 'Beginner',
    description: 'Build intuitive understanding of linear algebra matrices, eigenvalues, multivariate calculus, standard probability distributions, and statistics.',
    instructor: 'Dr. Satyajit Pattnaik',
    rating: 4.7,
    ratingCount: 856,
    price: '$10.99',
    originalPrice: '$39.99',
    duration: '11h 0m',
    tag: 'New',
    icon: '🧮',
    gradient: 'from-sky-500 to-indigo-700'
  },
  {
    id: 'ds-course-3',
    title: 'Python Data Science Toolkit: Pandas & NumPy',
    category: 'Data Science',
    level: 'Intermediate',
    description: 'Write vectorized matrix math operations, manipulate multi-index Pandas dataframes, parse time series, and clean unstructured data.',
    instructor: 'Dr. Satyajit Pattnaik',
    rating: 4.8,
    ratingCount: 1940,
    price: '$12.99',
    originalPrice: '$64.99',
    duration: '13h 25m',
    tag: 'Top Rated',
    icon: '📈',
    gradient: 'from-orange-500 to-red-600'
  },
  {
    id: 'ds-course-4',
    title: 'Interactive High-Fidelity Visualization with D3.js',
    category: 'Data Science',
    level: 'Intermediate',
    description: 'Construct bespoke multi-series charts, real-time update scatters, geospatial visual maps, and complex custom physics canvases from scratch.',
    instructor: 'Lead Instructor Kenji',
    rating: 4.7,
    ratingCount: 420,
    price: '$15.99',
    originalPrice: '$79.99',
    duration: '14h 15m',
    tag: '',
    icon: '🎨',
    gradient: 'from-pink-500 to-rose-600'
  },
  {
    id: 'ds-course-5',
    title: 'Applied Machine Learning & Feature Engineering',
    category: 'Data Science',
    level: 'Advanced',
    description: 'Train support vector machines, regression estimators, random forest ensembles, extreme gradient boosting (XGBoost), and perform cross-validation tuning.',
    instructor: 'Dr. Satyajit Pattnaik',
    rating: 4.8,
    ratingCount: 620,
    price: '$19.99',
    originalPrice: '$99.99',
    duration: '16h 40m',
    tag: 'Bestseller',
    icon: '🧬',
    gradient: 'from-teal-500 to-cyan-600'
  },
  {
    id: 'ds-course-6',
    title: 'Deep Learning & Neural Architectures with PyTorch',
    category: 'Data Science',
    level: 'Advanced',
    description: 'Construct deep linear networks, convolutional neural grids (CNN), recurrent sequence networks, configure backprop loss, and optimize weights.',
    instructor: 'Dr. Satyajit Pattnaik',
    rating: 4.9,
    ratingCount: 510,
    price: '$24.99',
    originalPrice: '$129.99',
    duration: '19h 10m',
    tag: 'Hot & New',
    icon: '🧠',
    gradient: 'from-amber-600 to-red-700'
  },
  {
    id: 'ds-course-7',
    title: 'AI Agents, RAG & LLM Evaluation for Production',
    category: 'Data Science',
    level: 'Expert',
    description: 'Build autonomous agentic AI loops, establish Retrieval-Augmented Generation semantic stores, and evaluate pipeline security using DeepEval & RAGAS.',
    instructor: 'Karthik KK',
    rating: 4.9,
    ratingCount: 659,
    price: '$10.99',
    originalPrice: '$19.99',
    duration: '15h 30m',
    tag: 'Bestseller',
    icon: '🤖',
    gradient: 'from-blue-600 to-violet-800'
  },
  {
    id: 'ds-course-8',
    title: 'Generative LLM Fine-Tuning & Hyper-Parameters',
    category: 'Data Science',
    level: 'Expert',
    description: 'Quantize open foundation LLMs (8bit/4bit), configure parameter-efficient LoRA adapters, set up alignment with DPO/PPO, and scale context buffers.',
    instructor: 'Dr. Satyajit Pattnaik',
    rating: 4.9,
    ratingCount: 150,
    price: '$49.99',
    originalPrice: '$299.99',
    duration: '24h 5m',
    tag: 'Top Rated',
    icon: '🌌',
    gradient: 'from-fuchsia-600 to-violet-950'
  }
];
